<a href="https://colab.research.google.com/github/Mahale-Pradnesh/Data-Science-and-Machine-Learning/blob/main/Numpy_Tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy :-Numerical Python**


Advantages of Numpy Arrays:

  1.Allow several Mathematical Operation
  
  2.Faster operation


In [1]:
import numpy as np

List vs Numpy :-Time Taken

In [3]:
from time import process_time

Time taken by list

In [8]:
from time import process_time
python_list=[i for i in range(10000)]


In [9]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time - start_time)




0.0006674740000001123


In [11]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array +=5

end_time=process_time()

print(end_time - start_time)

0.00013523099999979138


**Numpy Arrays**

In [15]:
# list
list1=[1,2,3,4,4]
print(list1)
type(list1)

[1, 2, 3, 4, 4]


list

In [17]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [18]:
# creating a 1 dimensional array
a=np.array([1,3,4,5,2])
print(a)

[1 3 4 5 2]


In [19]:
a.shape

(5,)

In [21]:
# creating a 2 dimensional array

b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
type(b)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [13]:
b.shape

(2, 4)

In [22]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


# Initial Placeholder to the numpy arrays

In [24]:
# Create a numpy array of a Zeros values

x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Create a numpy array of a Ones

y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a perticular values
s=np.full((3,5),7)
print(s)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
# create a identity matrix
d=np.eye((4))
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a array with a random values
b=np.random.random((3,5))
print(b)

[[0.81129429 0.51454265 0.53445592 0.87201506 0.77699586]
 [0.08601526 0.85233039 0.82318641 0.91224511 0.61932845]
 [0.85874931 0.96171584 0.82194402 0.36828175 0.84879181]]


In [ ]:
# random integer values array within a specific range
t=np.random.randint(10,100,(4,5))
print(t)

[[14 68 31 97 22]
 [25 85 91 48 25]
 [72 43 61 20 54]
 [72 38 27 64 79]]


In [ ]:
#array of evenly spaced values -->specifying the number of values requires
r=np.linspace(10,30,5)
print(r)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaced values -->specifying the step
r=np.arange(10,30,5)
print(r)

[10 15 20 25]


In [ ]:
#convert a list to a numpy array

list2=[10,20,30,40,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

# Analyzing Numpy Array:

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[40 71 66 37 19]
 [65 19 43 14 35]
 [63 50 89 72 44]
 [42 36 68 16 78]
 [82 43 82 50 77]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


# Mathematical Operations on np array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1 + list2) #Concatenate only

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[5 0 6]
 [6 2 6]
 [4 0 6]]
[[17 14 10]
 [18 14 19]
 [18 16 10]]


In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[22 14 16]
 [24 16 25]
 [22 16 16]]
[[-12 -14  -4]
 [-12 -12 -13]
 [-14 -16  -4]]
[[ 85   0  60]
 [108  28 114]
 [ 72   0  60]]
[[0.29411765 0.         0.6       ]
 [0.33333333 0.14285714 0.31578947]
 [0.22222222 0.         0.6       ]]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[6 1 9]
 [9 7 0]
 [3 5 4]]
[[19 19 16]
 [10 18 15]
 [19 16 14]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[25 20 25]
 [19 25 15]
 [22 21 18]]
[[-13 -18  -7]
 [ -1 -11 -15]
 [-16 -11 -10]]
[[114  19 144]
 [ 90 126   0]
 [ 57  80  56]]
[[0.31578947 0.05263158 0.5625    ]
 [0.9        0.38888889 0.        ]
 [0.15789474 0.3125     0.28571429]]


# Array Manipulation

In [ ]:
array=np.random.randint(0,10,(4,3))
print(array)
print(array.shape)

[[9 5 6]
 [6 2 6]
 [7 3 9]
 [1 0 4]]
(4, 3)


In [ ]:
# Transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[9 6 7 1]
 [5 2 3 0]
 [6 6 9 4]]
(3, 4)


In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 1 8]
 [1 0 7]]
(2, 3)


In [ ]:
trans2=array.T
print(trans2)
print(trans.shape)

[[0 1]
 [1 0]
 [8 7]]
(3, 2)


In [ ]:
# reshaping the array

a=np.random.randint(0,10,(4,3))
print(a)
print(a.shape)

[[6 6 6]
 [6 0 5]
 [9 5 1]
 [2 2 8]]
(4, 3)


In [ ]:
b=a.reshape(3,4)
print(b)
print(b.shape)

[[6 6 6 6]
 [0 5 9 5]
 [1 2 2 8]]
(3, 4)
